## api.config.yaml
---
apisix:
  node_listen:
    - 9080 # APISIX listening ports.

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd

  ## Admin API
  admin:
    allow_admin: # Limit Admin API access by IP addresses.
      - 0.0.0.0/0
    admin_key:
      - name: admin # admin: write access to configurations.
        key: "adminkey" #  API key for the admin of Admin API.
        role: admin
      - name: viewer # viewer: read access to configurations.
        key: "viewerkey" # API key for the viewer of Admin API.
        role: viewer
    admin_listen: # Admin API listening addresses.
      ip: 0.0.0.0 # Admin API listening IP.
      port: 9180 # Admin API listening port. Beware of port conflict with node_listen.

  ## etcd
  etcd:
    prefix: /apisix # etcd prefix.
    host: # etcd address(es) in the same etcd cluster.
      - http://etcd:2379

## Plugins
# plugin_attr:
#   limit-count:
#     redis:
#       host: "redis"
#       port: 6379
---

